Repository CropperBlazor/Cropper.Blazor, pull requests merged in 2023-11, with the labels that each got.

#251 Added Docs layout for API and contract
  src/Cropper.Blazor/Client/Enums/BasePage.cs
  src/Cropper.Blazor/Client/Services/LayoutService.cs
  src/Cropper.Blazor/Client/Services/MenuService.cs
  src/Cropper.Blazor/Client/Shared/DocsLayout.razor
  src/Cropper.Blazor/Client/Shared/DocsLayout.razor.cs
Labels: documentation, hacktoberfest-accepted, Hacktoberfest

#252 Feature/add basic and advanced usage cropping
  NuGet_README.md
  src/Cropper.Blazor/Client/Components/Docs/CodeInline.razor
  src/Cropper.Blazor/Client/Cropper.Blazor.Client.csproj
  src/Cropper.Blazor/Client/Pages/Crop/CropPage.razor
  src/Cropper.Blazor/Client/Pages/Crop/Examples/AdvancedCropExample.razor
  src/Cropper.Blazor/Client/Pages/Crop/Examples/BasicCropExample.razor
  src/Cropper.Blazor/Client/Pages/Index.razor
  src/Cropper.Blazor/Client/Services/MenuService.cs
  src/Cropper.Blazor/Client/Styles/components/docspage.scss
  src/Cropper.Blazor/Client/Styles/components/docssection.scss
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/DocStrings.cs
  src/Cropper.Blazor/Cropper.Blazor.Shared/Extensions/MethodInfoExtensions.cs
  src/Cropper.Blazor/Cropper.Blazor/Components/CropperComponent.razor.cs
  src/Cropper.Blazor/Cropper.Blazor/Cropper.Blazor.csproj
Labels: documentation, enhancement, hacktoberfest-accepted, Hacktoberfest

#253 docs: Fix loader styles. Fix title size
  src/Cropper.Blazor/Client/Pages/Index.razor
  src/Cropper.Blazor/Client/Styles/Cropper.Blazor.Client.scss
Labels: bug, documentation, hacktoberfest-accepted, Hacktoberfest

#256 Fix default values cropper component, update dependencies
  examples/Cropper.Blazor.MAUI.Net6/Cropper.Blazor.MAUI.Net6.csproj
  examples/Cropper.Blazor.MAUI.Net7/Cropper.Blazor.MAUI.Net7.csproj
  examples/Cropper.Blazor.Server.Net6/Cropper.Blazor.Server.Net6.csproj
  examples/Cropper.Blazor.Server.Net7/Cropper.Blazor.Server.Net7.csproj
  examples/Cropper.MVC.With.Blazor.Server.Net7/Cropper.MVC.With.Blazor.Server.Net7.csproj
  src/Cropper.Blazor/Client/Cropper.Blazor.Client.csproj
  src/Cropper.Blazor/Client/Pages/BasicUsage/BasicCropperUsagePage.razor
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/Cropper.Blazor.Client.Compiler.csproj
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Components/CropperComponent_Should.cs
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Cropper.Blazor.UnitTests.csproj
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Models/Options_Should.cs
  src/Cropper.Blazor/Cropper.Blazor/Components/CropperComponent.razor.cs
  src/Cropper.Blazor/Cropper.Blazor/Cropper.Blazor.csproj
  src/Cropper.Blazor/Cropper.Blazor/Models/GetCroppedCanvasOptions.cs
  src/Cropper.Blazor/Cropper.Blazor/Models/Options.cs
  src/Cropper.Blazor/Cropper.Blazor/wwwroot/cropperJsInterop.js
  src/Cropper.Blazor/Server/Cropper.Blazor.Server.csproj
Labels: documentation, enhancement, hacktoberfest-accepted, Hacktoberfest

#265 Feature/add cross-origin image loading example
  src/Cropper.Blazor/Client/Pages/BasicUsage/BasicCropperUsagePage.razor
  src/Cropper.Blazor/Client/Pages/BasicUsage/Examples/LoadCrossOriginImageExample.razor
Labels: documentation, enhancement

#268 Fix maui workloads
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  examples/Cropper.Blazor.Demo.sln
  examples/Cropper.Blazor.MAUI.Net6/Cropper.Blazor.MAUI.Net6.csproj
  examples/Cropper.Blazor.MAUI.Net7/Cropper.Blazor.MAUI.Net7.csproj
  examples/Cropper.Blazor.MAUI.Net8/Cropper.Blazor.MAUI.Net8.csproj
  src/Cropper.Blazor/Client/Cropper.Blazor.Client.csproj
Labels: bug

#269 Added stability to CI, CD, release pipelines
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  src/Cropper.Blazor/Client/Cropper.Blazor.Client.csproj
  src/Cropper.Blazor/Cropper.Blazor/Cropper.Blazor.csproj
Labels: bug, enhancement

#271 Feature/add releases
  src/Cropper.Blazor/Client/Enums/BasePage.cs
  src/Cropper.Blazor/Client/Models/GitHubAuthor.cs
  src/Cropper.Blazor/Client/Models/GitHubReleases.cs
  src/Cropper.Blazor/Client/Pages/CropperDemo.razor.css
  src/Cropper.Blazor/Client/Pages/Releases.razor
  src/Cropper.Blazor/Client/Pages/Releases.razor.cs
  src/Cropper.Blazor/Client/Program.cs
  src/Cropper.Blazor/Client/Services/GitHubApiClient.cs
  src/Cropper.Blazor/Client/Services/LayoutService.cs
  src/Cropper.Blazor/Client/Shared/Appbar.razor
  src/Cropper.Blazor/Client/Shared/DocsLayout.razor
  src/Cropper.Blazor/Client/Shared/Footer.razor
  src/Cropper.Blazor/Client/Shared/LandingLayout.razor
  src/Cropper.Blazor/Client/Styles/Cropper.Blazor.Client.scss
Labels: documentation

#272 DOCS: Add preview page example, fix stability CD with OpenJDK version
  .github/workflows/cd.yml
  src/Cropper.Blazor/Client/Components/Docs/DocsPage.razor.cs
  src/Cropper.Blazor/Client/Extensions/NavigationManagerExtensions.cs
  src/Cropper.Blazor/Client/Pages/Home/Uses/Examples/UsesPreviewFromElementReferenceSelectorComponentsExample.razor.css
  src/Cropper.Blazor/Client/Pages/Home/Uses/Examples/UsesPreviewFromElementReferenceSelectorComponentsExampleCode.html
  src/Cropper.Blazor/Client/Pages/Home/Uses/Examples/UsesPreviewFromMultipleElementReferenceSelectorComponentsExample.razor.css
  src/Cropper.Blazor/Client/Pages/Home/Uses/Examples/UsesPreviewFromMultipleElementReferenceSelectorComponentsExampleCode.html
  src/Cropper.Blazor/Client/Pages/Home/Uses/Examples/UsesPreviewFromStringSelectorComponentsExample.razor
  src/Cropper.Blazor/Client/Pages/Home/Uses/Examples/UsesPreviewFromStringSelectorComponentsExample.razor.css
  src/Cropper.Blazor/Client/Pages/Home/Uses/Examples/UsesPreviewFromStringSelectorComponentsExampleCode.html
  src/Cropper.Blazor/Client/Pages/Index.razor
  src/Cropper.Blazor/Client/Pages/Index.razor.cs
  src/Cropper.Blazor/Client/Pages/Preview/CropperPreviewPage.razor
  src/Cropper.Blazor/Client/Pages/Preview/Examples/UsesPreviewFromElementReferenceSelectorComponentsExample.razor
  src/Cropper.Blazor/Client/Pages/Preview/Examples/UsesPreviewFromMultipleElementReferenceSelectorComponentsExample.razor
  src/Cropper.Blazor/Client/Pages/Preview/Examples/UsesPreviewFromStringSelectorComponentsExample.razor
  src/Cropper.Blazor/Client/Services/MenuService.cs
Labels: documentation, enhancement

#281 Add maui notes
  src/Cropper.Blazor/Client/Pages/About.razor
  src/Cropper.Blazor/Client/Pages/Home/Installation/Examples/DotnetWorkloadUpdateCommandExample.razor
  src/Cropper.Blazor/Client/Pages/Home/Installation/Examples/InstallServicesForBlazorServerExampleCode.html
  src/Cropper.Blazor/Client/Pages/Home/Installation/Examples/InstallationManualComponentsExampleCode.html
  src/Cropper.Blazor/Client/Pages/Home/Installation/Examples/InstallationManualCssFontsExampleCode.html
  src/Cropper.Blazor/Client/Pages/Home/Installation/Examples/InstallationManualImportsExampleCode.html
  src/Cropper.Blazor/Client/Pages/Home/Installation/Examples/InstallationManualPackageExampleCode.html
  src/Cropper.Blazor/Client/Pages/Home/Installation/Examples/VersionOverridePackageReferenceCommandExample.razor
  src/Cropper.Blazor/Client/Pages/Index.razor
  src/Cropper.Blazor/Client/Shared/Appbar.razor
  src/Cropper.Blazor/Client/Shared/Footer.razor
  src/Cropper.Blazor/Client/Shared/LandingLayout.razor.cs
Labels: documentation
