Repository CropperBlazor/Cropper.Blazor, pull requests merged in 2023-10, with the labels that each got.

#232 Feature/add docs links part 4
  src/Cropper.Blazor/Client/Components/Docs/ApiProperty.cs
  src/Cropper.Blazor/Client/Components/Docs/DocsApi.razor
  src/Cropper.Blazor/Client/Components/Docs/DocsApi.razor.cs
  src/Cropper.Blazor/Client/Components/Docs/DocsTypeInfo.razor
  src/Cropper.Blazor/Client/Models/DocStrings.cs
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/DocStrings.cs
  src/Cropper.Blazor/Cropper.Blazor.Shared/Extensions/MethodInfoExtensions.cs
  src/Cropper.Blazor/Cropper.Blazor.Shared/Extensions/XmlDocumentationExtension.cs
Labels: Hacktoberfest

#233 Update cropper js to 1.6.1, update dependencies
  README.md
  examples/Cropper.Blazor.MAUI.Net6/Cropper.Blazor.MAUI.Net6.csproj
  examples/Cropper.Blazor.MAUI.Net7/Cropper.Blazor.MAUI.Net7.csproj
  examples/Cropper.Blazor.Server.Net6/Cropper.Blazor.Server.Net6.csproj
  examples/Cropper.Blazor.Server.Net7/Cropper.Blazor.Server.Net7.csproj
  examples/Cropper.MVC.With.Blazor.Server.Net7/Cropper.MVC.With.Blazor.Server.Net7.csproj
  src/Cropper.Blazor/Client/Cropper.Blazor.Client.csproj
  src/Cropper.Blazor/Client/Pages/Index.razor
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/DocStrings.cs
  src/Cropper.Blazor/Cropper.Blazor.Testing/Cropper.Blazor.Testing.csproj
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Cropper.Blazor.UnitTests.csproj
  src/Cropper.Blazor/Cropper.Blazor/Cropper.Blazor.csproj
  src/Cropper.Blazor/Cropper.Blazor/wwwroot/cropper.min.css
  src/Cropper.Blazor/Cropper.Blazor/wwwroot/cropper.min.js
  src/Cropper.Blazor/Server/Cropper.Blazor.Server.csproj
Labels: documentation, enhancement, hacktoberfest-accepted, Hacktoberfest

#235 Feature/update to 1 2 6
  .github/CODE_OF_CONDUCT.md
  README.md
  examples/Cropper.Blazor.MAUI.Net6/Cropper.Blazor.MAUI.Net6.csproj
  examples/Cropper.Blazor.MAUI.Net7/Cropper.Blazor.MAUI.Net7.csproj
  examples/Cropper.Blazor.Server.Net6/Cropper.Blazor.Server.Net6.csproj
  examples/Cropper.Blazor.Server.Net7/Cropper.Blazor.Server.Net7.csproj
  examples/Cropper.MVC.With.Blazor.Server.Net7/Cropper.MVC.With.Blazor.Server.Net7.csproj
  src/Cropper.Blazor/Client/Components/CroppedDimensionsSettings.razor
  src/Cropper.Blazor/Client/Components/Docs/ApiLink.cs
  src/Cropper.Blazor/Client/Components/Docs/ApiProperty.cs
  src/Cropper.Blazor/Client/Components/Docs/DocsApi.razor
  src/Cropper.Blazor/Client/Components/Docs/DocsApi.razor.cs
  src/Cropper.Blazor/Client/Components/Docs/DocsPage.razor
  src/Cropper.Blazor/Client/Components/Docs/DocsTypeInfo.razor
  src/Cropper.Blazor/Client/Components/ZoomRatioSettings.razor
  src/Cropper.Blazor/Client/Components/ZoomRatioSettings.razor.cs
  src/Cropper.Blazor/Client/Cropper.Blazor.Client.csproj
  src/Cropper.Blazor/Client/Models/DocStrings.cs
  src/Cropper.Blazor/Client/Pages/DataContract.razor
  src/Cropper.Blazor/Client/Pages/DataContract.razor.cs
  src/Cropper.Blazor/Client/Pages/Examples/Installation/InstallationManualComponentsExample.razor
  src/Cropper.Blazor/Client/Pages/Examples/Installation/InstallationManualComponentsExampleCode.html
  src/Cropper.Blazor/Client/Pages/Examples/Uses/Preview/UsesPreviewFromElementReferenceSelectorComponentsExample.razor
  src/Cropper.Blazor/Client/Pages/Examples/Uses/Preview/UsesPreviewFromElementReferenceSelectorComponentsExampleCode.html
  src/Cropper.Blazor/Client/Pages/Examples/Uses/Preview/UsesPreviewFromMultipleElementReferenceSelectorComponentsExample.razor
  src/Cropper.Blazor/Client/Pages/Examples/Uses/Preview/UsesPreviewFromMultipleElementReferenceSelectorComponentsExampleCode.html
  src/Cropper.Blazor/Client/Pages/Examples/Uses/Preview/UsesPreviewFromStringSelectorComponentsExample.razor
  src/Cropper.Blazor/Client/Pages/Examples/Uses/Preview/UsesPreviewFromStringSelectorComponentsExampleCode.html
  src/Cropper.Blazor/Client/Pages/Index.razor
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/DocStrings.cs
  src/Cropper.Blazor/Cropper.Blazor.Shared/Extensions/MethodInfoExtensions.cs
  src/Cropper.Blazor/Cropper.Blazor.Shared/Extensions/TypeNameHelper.cs
  src/Cropper.Blazor/Cropper.Blazor.Shared/Extensions/XmlDocumentationExtension.cs
  src/Cropper.Blazor/Cropper.Blazor.Testing/Cropper.Blazor.Testing.csproj
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Cropper.Blazor.UnitTests.csproj
  src/Cropper.Blazor/Cropper.Blazor.sln
  src/Cropper.Blazor/Cropper.Blazor/Components/CropperComponent.razor.cs
  src/Cropper.Blazor/Cropper.Blazor/Cropper.Blazor.csproj
  src/Cropper.Blazor/Cropper.Blazor/wwwroot/cropper.min.css
  src/Cropper.Blazor/Cropper.Blazor/wwwroot/cropper.min.js
  src/Cropper.Blazor/Server/Cropper.Blazor.Server.csproj
Labels: hacktoberfest-accepted, Hacktoberfest

#238 Add links for examples
  src/Cropper.Blazor/Client/Components/Docs/DocsApi.razor
  src/Cropper.Blazor/Client/Pages/AspectRatio/AspectRatioPage.razor
  src/Cropper.Blazor/Client/Pages/BasicUsage/BasicCropperUsagePage.razor
  src/Cropper.Blazor/Client/Pages/CropBoxDimensions/CropBoxDimensionsPage.razor
  src/Cropper.Blazor/Client/Pages/CropZoom/CropperZoomPage.razor
  src/Cropper.Blazor/Client/Pages/ViewModes/ViewModesPage.razor
Labels: hacktoberfest-accepted, Hacktoberfest

#239 Feature/increase coverage unit tests
  .github/codecov.yml
  README.md
  src/Cropper.Blazor/Client/Pages/About.razor
  src/Cropper.Blazor/Client/Pages/CropperDemo.razor
  src/Cropper.Blazor/Client/Pages/CropperDemo.razor.cs
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Components/CropperComponent_Should.cs
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Events/CropEndEvent/CropEndEvent_Should.cs
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Events/CropMoveEvent/CropMoveEvent_Should.cs
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Events/CropStartEvent/CropStartEvent_Should.cs
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Events/ZoomEvent/ZoomEvent_Should.cs
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Models/CroppedCanvas_Should.cs
  src/Cropper.Blazor/Cropper.Blazor/Components/CropperComponent.razor.cs
  src/Cropper.Blazor/Cropper.Blazor/Extensions/ServiceCollectionExtensions.cs
Labels: hacktoberfest-accepted, Hacktoberfest

#240 Optimize cd pipeline
  .github/workflows/cd.yml
Labels: enhancement, hacktoberfest-accepted, Hacktoberfest

#242 docs: Create footer, routing to examples page fix
  src/Cropper.Blazor/Client/Components/Docs/DocsPage.razor
  src/Cropper.Blazor/Client/Models/Snippets.cs
  src/Cropper.Blazor/Client/Pages/BasicUsage/BasicCropperUsagePage.razor
  src/Cropper.Blazor/Client/Pages/ManualMarkdown/InstallServicesNET6Manual.razor
  src/Cropper.Blazor/Client/Shared/Appbar.razor
  src/Cropper.Blazor/Client/Shared/Appbar.razor.cs
  src/Cropper.Blazor/Client/Shared/DocsLayout.razor
  src/Cropper.Blazor/Client/Shared/DocsLayout.razor.cs
  src/Cropper.Blazor/Client/Shared/Footer.razor
  src/Cropper.Blazor/Client/Shared/LandingLayout.razor
  src/Cropper.Blazor/Client/Shared/LandingLayout.razor.cs
Labels: hacktoberfest-accepted, Hacktoberfest

#243 docs: Fix loader scss styles
  src/Cropper.Blazor/Client/Styles/Cropper.Blazor.Client.scss
Labels: hacktoberfest-accepted, Hacktoberfest

#244 docs: navmenu fix
  src/Cropper.Blazor/Client/Services/MenuService.cs
  src/Cropper.Blazor/Client/Shared/NavMenu.razor
Labels: hacktoberfest-accepted, Hacktoberfest

#245 Update README.md
  README.md
Labels: hacktoberfest-accepted, Hacktoberfest
