Repository CropperBlazor/Cropper.Blazor, pull requests merged in 2024-08, with the labels that each got.

#343 Fix broken links
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/DocStrings.cs
  src/Cropper.Blazor/Cropper.Blazor.Shared/Extensions/MethodInfoExtensions.cs
Labels: documentation

#342 Update pipelines. Create .editorconfig
  .github/dependabot.yml
  .github/linters/.jscpd.json
  .github/workflows/build-test-template.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/dependabot-ci.yml
  .github/workflows/release.yml
  src/Cropper.Blazor/.editorconfig
  src/Cropper.Blazor/Cropper.Blazor.sln
Labels: enhancement, dependencies

#345 Fix all docs API issues
  src/Cropper.Blazor/Client/Components/Docs/ApiLink.cs
  src/Cropper.Blazor/Client/Components/Docs/DocsApi.razor
  src/Cropper.Blazor/Client/Components/Docs/DocsTypeInfo.razor
  src/Cropper.Blazor/Client/Pages/DataContract.razor
  src/Cropper.Blazor/Client/Services/MenuService.cs
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/DocStrings.cs
  src/Cropper.Blazor/Cropper.Blazor.Shared/Extensions/MethodInfoExtensions.cs
  src/Cropper.Blazor/Cropper.Blazor/Components/CropperComponent.razor.cs
Labels: documentation, enhancement

#351 Fix linter errors
  .gitattributes
  .github/linters/.stylelintrc.json
  .github/workflows/build-test-template.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  src/Cropper.Blazor/Client/.config/dotnet-tools.json
  src/Cropper.Blazor/Client/Components/Docs/ApiLink.cs
  src/Cropper.Blazor/Client/Components/Docs/DocsApi.razor.cs
  src/Cropper.Blazor/Client/Components/Docs/SectionContent.razor.cs
  src/Cropper.Blazor/Client/Cropper.Blazor.Client.csproj
  src/Cropper.Blazor/Client/Pages/Crop/Examples/CropPolygonImage_ScriptCode.html
  src/Cropper.Blazor/Client/Pages/Crop/Examples/CropRoundImage_ScriptCode.html
  src/Cropper.Blazor/Client/Pages/CropZoom/Examples/MinMaxZoomRatio_ScriptCode.html
  src/Cropper.Blazor/Client/Pages/CropperDemo.razor.cs
  src/Cropper.Blazor/Client/Pages/CropperDemo.razor.css
  src/Cropper.Blazor/Client/Pages/ManualMarkdown/InstallScriptManualCode.html
  src/Cropper.Blazor/Client/Pages/ManualMarkdown/InstallServicesForBlazorServerManualCode.html
  src/Cropper.Blazor/Client/Pages/ManualMarkdown/InstallServicesManualCode.html
  src/Cropper.Blazor/Client/Pages/ManualMarkdown/InstallServicesOverrideGlobalCode.html
  src/Cropper.Blazor/Client/Pages/ManualMarkdown/InstallServicesOverrideInternalCode.html
  src/Cropper.Blazor/Client/Shared/CroppedCanvasDialog.razor.cs
  src/Cropper.Blazor/Client/Shared/SeoHeader.razor.cs
  src/Cropper.Blazor/Client/Shared/Utilities/CropperBlazorLogo.razor
  src/Cropper.Blazor/Client/Styles/Cropper.Blazor.Client.scss
  src/Cropper.Blazor/Client/Styles/components/docspage.scss
  src/Cropper.Blazor/Client/Styles/components/docssection.scss
  src/Cropper.Blazor/Client/Styles/layout/mainlayout.scss
  src/Cropper.Blazor/Client/Styles/layout/markdown.scss
  src/Cropper.Blazor/Client/Styles/layout/updateAvaibleDetector.scss
  src/Cropper.Blazor/Client/wwwroot/helper.js
  src/Cropper.Blazor/Client/wwwroot/index.html
  src/Cropper.Blazor/Client/wwwroot/jsObjectModule.js
  src/Cropper.Blazor/Client/wwwroot/overrideCropperJsInteropModule.js
  src/Cropper.Blazor/Client/wwwroot/resizeWindowEventListener.js
  src/Cropper.Blazor/Client/wwwroot/service-worker.js
  src/Cropper.Blazor/Client/wwwroot/service-worker.published.js
  src/Cropper.Blazor/Client/wwwroot/sw-registrator.js
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/CodeSnippetsCompiler.cs
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/Cropper.Blazor.Client.Compiler.csproj
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/DocStrings.cs
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/ExamplesMarkup.cs
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/Paths.cs
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/Program.cs
  src/Cropper.Blazor/Cropper.Blazor.Client.Compiler/StyleDictionary.KebabCase.cs
  src/Cropper.Blazor/Cropper.Blazor.Shared/Cropper.Blazor.Shared.csproj
  src/Cropper.Blazor/Cropper.Blazor.Shared/Extensions/TypeNameHelper.cs
  src/Cropper.Blazor/Cropper.Blazor.Shared/Extensions/XmlDocumentationExtension.cs
  src/Cropper.Blazor/Cropper.Blazor.Sitemap.Generator/Cropper.Blazor.Sitemap.Generator.csproj
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Cropper.Blazor.UnitTests.csproj
  src/Cropper.Blazor/Cropper.Blazor.UnitTests/Services/CropperJsInterop_Should.cs
  src/Cropper.Blazor/Cropper.Blazor/.config/dotnet-tools.json
  src/Cropper.Blazor/Cropper.Blazor/wwwroot/cropperJsInterop.js
  src/Cropper.Blazor/Server/Cropper.Blazor.Server.csproj
Labels: documentation, enhancement, dependencies

#359 fix pipelines, add more setting for dependabot.yml
  .github/dependabot.yml
  .github/workflows/release.yml
Labels: enhancement

#360 Fix Release and Dependabot pipelines
  .github/dependabot.yml
  .github/workflows/release.yml
Labels: enhancement

#362 fix pack files
  .github/workflows/release.yml
  src/Cropper.Blazor/Cropper.Blazor/Cropper.Blazor.csproj
Labels: enhancement

#363 Remove redundant file from NuGet
  src/Cropper.Blazor/Cropper.Blazor/wwwroot/background.png
Labels: enhancement

#364 Remove redundant file from NuGet, roll out new version
  .github/dependabot.yml
  .github/workflows/release.yml
  src/Cropper.Blazor/Cropper.Blazor/Cropper.Blazor.csproj
  src/Cropper.Blazor/Cropper.Blazor/wwwroot/background.png
Labels: bug, enhancement
